AX_ROLE = "AXRole"
AX_SUBROLE = "AXSubrole"
AX_TITLE = "AXTitle"
AX_DESCRIPTION = "AXDescription"
AX_VALUE = "AXValue"
AX_ENABLED = "AXEnabled"
AX_HIDDEN = "AXHidden"
AX_FOCUSED = "AXFocused"
AX_SELECTED = "AXSelected"
AX_EXPANDED = "AXExpanded"
AX_IDENTIFIER = "AXIdentifier"
AX_CHILDREN = "AXChildren"
AX_PARENT = "AXParent"

AX_PRESS = "AXPress"
AX_INCREMENT = "AXIncrement"
AX_DECREMENT = "AXDecrement"
AX_SHOW_MENU = "AXShowMenu"
AX_RAISE = "AXRaise"

AX_SCROLL_UP = "AXScrollUp"
AX_SCROLL_DOWN = "AXScrollDown"

ROLE_BUTTON = "AXButton"
ROLE_CHECKBOX = "AXCheckBox"
ROLE_COMBOBOX = "AXComboBox"
ROLE_DISCLOSURE_TRIANGLE = "AXDisclosureTriangle"
ROLE_GROUP = "AXGroup"
ROLE_LINK = "AXLink"
ROLE_LIST = "AXList"
ROLE_MENU_ITEM = "AXMenuItem"
ROLE_OUTLINE = "AXOutline"
ROLE_POPUP_BUTTON = "AXPopUpButton"
ROLE_RADIO_BUTTON = "AXRadioButton"
ROLE_SCROLL_AREA = "AXScrollArea"
ROLE_SLIDER = "AXSlider"
ROLE_SPLITTER = "AXSplitter"
ROLE_STEPPER = "AXIncrementor"
ROLE_TAB = "AXTab"
ROLE_TABLE = "AXTable"
ROLE_TEXT_AREA = "AXTextArea"
ROLE_TEXT_FIELD = "AXTextField"
ROLE_WINDOW = "AXWindow"

TEXT_ROLES = frozenset({ROLE_TEXT_FIELD, ROLE_TEXT_AREA, ROLE_COMBOBOX})
TOGGLE_ROLES = frozenset({ROLE_CHECKBOX, ROLE_RADIO_BUTTON})
SCROLLABLE_ROLES = frozenset(
    {ROLE_SCROLL_AREA, ROLE_LIST, ROLE_OUTLINE, ROLE_TABLE, ROLE_TEXT_AREA}
)
